version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: learnpath_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: learnpath
      POSTGRES_PASSWORD: learnpath_secret
      POSTGRES_DB: learnpath
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
