const extractId = (url) => {
  const match = url.match(/v=([^&]+)/);
  return match ? match[1] : url.split("/").pop();
};

const courses = [
  {
    name: "Java Crash Course",
    videos: [
      "https://www.youtube.com/watch?v=7-lK9EpBS_Y"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Multithreading",
    videos: [
      "https://www.youtube.com/watch?v=091vJWjl1A4",
      "https://www.youtube.com/watch?v=OxXhqOJ-o30",
      "https://www.youtube.com/watch?v=H7wi8n3cUx0",
      "https://www.youtube.com/watch?v=3N5Js9k3tm4",
      "https://www.youtube.com/watch?v=Ljqs8kUJKZs",
      "https://www.youtube.com/watch?v=7MSazrWWV8g",
      "https://www.youtube.com/watch?v=ge6_41ZRr_w",
      "https://www.youtube.com/watch?v=ay5ynKnI9vc",
      "https://www.youtube.com/watch?v=Iv5cP97OXlA",
      "https://www.youtube.com/watch?v=ShwECPIpkhY",
      "https://www.youtube.com/watch?v=Ee42spqUzbE",
      "https://www.youtube.com/watch?v=mr9gkYUQjCI",
      "https://www.youtube.com/watch?v=KmqmoEhyFtM",
      "https://www.youtube.com/watch?v=-i5Pb3rCIkc",
      "https://www.youtube.com/watch?v=3HE8D9g9QNE",
      "https://www.youtube.com/watch?v=ip68xxgffC8",
      "https://www.youtube.com/watch?v=2GMgETsrfZ8",
      "https://www.youtube.com/watch?v=2jAPHlAK1Z0",
      "https://www.youtube.com/watch?v=JoYFkYqE8S0",
      "https://www.youtube.com/watch?v=WDn_Bax0UFo",
      "https://www.youtube.com/watch?v=IcvAVzsq_Ng"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Collections",
    videos: [
      "https://www.youtube.com/watch?v=091vJWjl1A4",
      "https://www.youtube.com/watch?v=OxXhqOJ-o30",
      "https://www.youtube.com/watch?v=H7wi8n3cUx0",
      "https://www.youtube.com/watch?v=3N5Js9k3tm4",
      "https://www.youtube.com/watch?v=Ljqs8kUJKZs",
      "https://www.youtube.com/watch?v=7MSazrWWV8g",
      "https://www.youtube.com/watch?v=ge6_41ZRr_w",
      "https://www.youtube.com/watch?v=ay5ynKnI9vc",
      "https://www.youtube.com/watch?v=Iv5cP97OXlA",
      "https://www.youtube.com/watch?v=ShwECPIpkhY",
      "https://www.youtube.com/watch?v=Ee42spqUzbE",
      "https://www.youtube.com/watch?v=mr9gkYUQjCI",
      "https://www.youtube.com/watch?v=KmqmoEhyFtM",
      "https://www.youtube.com/watch?v=-i5Pb3rCIkc",
      "https://www.youtube.com/watch?v=3HE8D9g9QNE",
      "https://www.youtube.com/watch?v=ip68xxgffC8",
      "https://www.youtube.com/watch?v=2GMgETsrfZ8",
      "https://www.youtube.com/watch?v=2jAPHlAK1Z0",
      "https://www.youtube.com/watch?v=JoYFkYqE8S0",
      "https://www.youtube.com/watch?v=WDn_Bax0UFo",
      "https://www.youtube.com/watch?v=IcvAVzsq_Ng"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Git/GitHub",
    videos: [
      "https://www.youtube.com/watch?v=-3SMW-3Z4OM",
      "https://www.youtube.com/watch?v=BHATRdSj7TA",
      "https://www.youtube.com/watch?v=HMz2X4stnwM",
      "https://www.youtube.com/watch?v=SaY56A-sa6o",
      "https://www.youtube.com/watch?v=VLROY9AX1ag",
      "https://www.youtube.com/watch?v=bT_pACeKdc0",
      "https://www.youtube.com/watch?v=jMXggIJtCXI",
      "https://www.youtube.com/watch?v=sjHiFm0ZZ4s",
      "https://www.youtube.com/watch?v=b8B5JgiN4Dw",
      "https://www.youtube.com/watch?v=1nUm8lUpPNA",
      "https://www.youtube.com/watch?v=1GvLkKe32-w",
      "https://www.youtube.com/watch?v=DRlvtr8D7yA",
      "https://www.youtube.com/watch?v=hKZOeABhlio",
      "https://www.youtube.com/watch?v=rQXwcbO636U",
      "https://www.youtube.com/watch?v=xgkXgBKIPpA",
      "https://www.youtube.com/watch?v=ZoFEubSBzDc",
      "https://www.youtube.com/watch?v=zT4j1BsdhPs",
      "https://www.youtube.com/watch?v=e2wy-j1CVJ8"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "MySQL",
    videos: [
      "https://www.youtube.com/watch?v=VWugHKeYhNk",
      "https://www.youtube.com/watch?v=CKs5LtvyQiU",
      "https://www.youtube.com/watch?v=-MmgWh217AY",
      "https://www.youtube.com/watch?v=KFgfpkUob0E",
      "https://www.youtube.com/watch?v=knKhj6_5cZA",
      "https://www.youtube.com/watch?v=wF7-GB4iHLQ",
      "https://www.youtube.com/watch?v=uStOz4qJXJ0",
      "https://www.youtube.com/watch?v=2nxKlUCyRS4",
      "https://www.youtube.com/watch?v=0v8Z4ZybxHo",
      "https://www.youtube.com/watch?v=Lj7dAPWcpr0",
      "https://www.youtube.com/watch?v=bfQZI1gk6qM",
      "https://www.youtube.com/watch?v=0OwEUHAGGqM",
      "https://www.youtube.com/watch?v=JWlh_OIPH1c",
      "https://www.youtube.com/watch?v=9Rw4sUKn5mM",
      "https://www.youtube.com/watch?v=fVAZ7LcPOvw",
      "https://www.youtube.com/watch?v=Hf9O8oNnHg8",
      "https://www.youtube.com/watch?v=xIqMC4CjGvY",
      "https://www.youtube.com/watch?v=YrF8QEL-xuc",
      "https://www.youtube.com/watch?v=0DhykMld5Mk",
      "https://www.youtube.com/watch?v=suKHq3ZLPmU",
      "https://www.youtube.com/watch?v=lQBhzBhkGww",
      "https://www.youtube.com/watch?v=xYEfkyoNBDU",
      "https://www.youtube.com/watch?v=ZRVhTrhcwwA",
      "https://www.youtube.com/watch?v=QHKBC2YkdwA",
      "https://www.youtube.com/watch?v=D5MV7epXRnI"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "MongoDB",
    videos: [
      "https://www.youtube.com/watch?v=4EjKroJCpFA",
      "https://www.youtube.com/watch?v=f43Q7SoxPl4",
      "https://www.youtube.com/watch?v=P0PbaTKm3Ok",
      "https://www.youtube.com/watch?v=Hvju9iIpGDM",
      "https://www.youtube.com/watch?v=Llllssq-3g8",
      "https://www.youtube.com/watch?v=2Qj33fkKRo0",
      "https://www.youtube.com/watch?v=IFMfHhhq0ls",
      "https://www.youtube.com/watch?v=cA917b2wxvE",
      "https://www.youtube.com/watch?v=WC5Q2IpKtCQ",
      "https://www.youtube.com/watch?v=Cjr-gkQSii8",
      "https://www.youtube.com/watch?v=W_1zgvqwx80",
      "https://www.youtube.com/watch?v=7D17DVmMrpE",
      "https://www.youtube.com/watch?v=-mYB6Ym8ZIc",
      "https://www.youtube.com/watch?v=Eemjm6H2dGk",
      "https://www.youtube.com/watch?v=UaLiC6z1JIU",
      "https://www.youtube.com/watch?v=6Cv7ihA4388",
      "https://www.youtube.com/watch?v=3slJKBYEgbU",
      "https://www.youtube.com/watch?v=k5KuDcsp39k",
      "https://www.youtube.com/watch?v=I0fxhB81nqc",
      "https://www.youtube.com/watch?v=OjMJgW4hby8",
      "https://www.youtube.com/watch?v=FAInqdJlu2k",
      "https://www.youtube.com/watch?v=2ur6Cs8OPSU",
      "https://www.youtube.com/watch?v=Hs8AM57BlVc",
      "https://www.youtube.com/watch?v=wPL2i8KHKTI",
      "https://www.youtube.com/watch?v=eYE3vkR1mGA",
      "https://www.youtube.com/watch?v=yNQ20_RfwUk",
      "https://www.youtube.com/watch?v=N2vaL3Oz--E",
      "https://www.youtube.com/watch?v=yo6ZXsgsyBA",
      "https://www.youtube.com/watch?v=MWmMvudBgFU",
      "https://www.youtube.com/watch?v=ga8LeVRmtG0",
      "https://www.youtube.com/watch?v=zzVa5cvQK6w",
      "https://www.youtube.com/watch?v=9sUBVbQY4b8",
      "https://www.youtube.com/watch?v=khq2wvnWo5M",
      "https://www.youtube.com/watch?v=1HBp3WYhx8Y",
      "https://www.youtube.com/watch?v=bSulWZtc2n8",
      "https://www.youtube.com/watch?v=LqCEp1PmfgY",
      "https://www.youtube.com/watch?v=ErszXERETr0",
      "https://www.youtube.com/watch?v=ZFhLaufhxYg",
      "https://www.youtube.com/watch?v=j7Ke_tvOtgE"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Spring (Core)",
    videos: [
      "https://www.youtube.com/watch?v=tRagsACyKkw",
      "https://www.youtube.com/watch?v=p0vfKL_pZgo",
      "https://www.youtube.com/watch?v=OniANMLe720",
      "https://www.youtube.com/watch?v=Z7lYkaD_S_I",
      "https://www.youtube.com/watch?v=PIxCOOPcDTc",
      "https://www.youtube.com/watch?v=xpSgBoEeHaI",
      "https://www.youtube.com/watch?v=IIVWgJuwyMs",
      "https://www.youtube.com/watch?v=RlzgALbImS0",
      "https://www.youtube.com/watch?v=u4DlNvD3NNI",
      "https://www.youtube.com/watch?v=DKnycBwmXsg",
      "https://www.youtube.com/watch?v=AMCvs_f_kDQ",
      "https://www.youtube.com/watch?v=FuFGBHAW3gQ",
      "https://www.youtube.com/watch?v=Zq_z3VeGeuI",
      "https://www.youtube.com/watch?v=U_JYmvwKKqs",
      "https://www.youtube.com/watch?v=tU_UNn90VcM",
      "https://www.youtube.com/watch?v=wXsifghAb30",
      "https://www.youtube.com/watch?v=rWEK20EMyZ8",
      "https://www.youtube.com/watch?v=Ey5uNTTdjNk",
      "https://www.youtube.com/watch?v=HRAaAhb5Ucc",
      "https://www.youtube.com/watch?v=GYd0u-qEaKU",
      "https://www.youtube.com/watch?v=xYyGA5hKMIQ",
      "https://www.youtube.com/watch?v=yJTKL1dSrKE",
      "https://www.youtube.com/watch?v=AOmMJoKZYPc"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Spring Boot",
    videos: [
      "https://www.youtube.com/watch?v=1993zSY5UBI",
      "https://www.youtube.com/watch?v=QZWCbxm9G28",
      "https://www.youtube.com/watch?v=vW-DTk--qEM",
      "https://www.youtube.com/watch?v=d4dcV7Kt3SI",
      "https://www.youtube.com/watch?v=p0vfKL_pZgo",
      "https://www.youtube.com/watch?v=zAmMPM8dIXc",
      "https://www.youtube.com/watch?v=JNzVOpNCcfw",
      "https://www.youtube.com/watch?v=99M7TJvijUk",
      "https://www.youtube.com/watch?v=rxT5RFYxjSg",
      "https://www.youtube.com/watch?v=LtnVqa5dYLA",
      "https://www.youtube.com/watch?v=3Dc8YxC0p-s",
      "https://www.youtube.com/watch?v=ddrCOI0buBA",
      "https://www.youtube.com/watch?v=jvSicVdHKT8",
      "https://www.youtube.com/watch?v=tWBhE1Cn8D0",
      "https://www.youtube.com/watch?v=xmRjF9qycIk",
      "https://www.youtube.com/watch?v=Cx81dki8BTA",
      "https://www.youtube.com/watch?v=6oxyNgZSz9s",
      "https://www.youtube.com/watch?v=HjDyv7gL4Wg",
      "https://www.youtube.com/watch?v=jJ5qrkMQ6r8",
      "https://www.youtube.com/watch?v=02WP1FbiNSQ",
      "https://www.youtube.com/watch?v=QrCVj8ek83k",
      "https://www.youtube.com/watch?v=LndqWC4yIU4",
      "https://www.youtube.com/watch?v=rbORgxkBWSk",
      "https://www.youtube.com/watch?v=mILLHaIjGn4",
      "https://www.youtube.com/watch?v=YcAC59cvcV0",
      "https://www.youtube.com/watch?v=WRUVixDFI6s",
      "https://www.youtube.com/watch?v=bphMYrTv8pA",
      "https://www.youtube.com/watch?v=iZtA-1zBvzY",
      "https://www.youtube.com/watch?v=95zTDdXbl_Q",
      "https://www.youtube.com/watch?v=NwADDLFs_SU",
      "https://www.youtube.com/watch?v=bvBuqw7Skh0",
      "https://www.youtube.com/watch?v=eAoX9wNT3Bo",
      "https://www.youtube.com/watch?v=BqIpcX2zlWc",
      "https://www.youtube.com/watch?v=KSrXndTbVVQ",
      "https://www.youtube.com/watch?v=EL2ouT5P4Lc",
      "https://www.youtube.com/watch?v=42rA_GOlLHA",
      "https://www.youtube.com/watch?v=9aP0qD3jG_8",
      "https://www.youtube.com/watch?v=AIgjFvRr820",
      "https://www.youtube.com/watch?v=2srQ-RiJHps",
      "https://www.youtube.com/watch?v=13HUNj8lHC0",
      "https://www.youtube.com/watch?v=2YnutJ8tNos",
      "https://www.youtube.com/watch?v=qvAoUVXgpZg",
      "https://www.youtube.com/watch?v=OG9vXOQsi5k",
      "https://www.youtube.com/watch?v=Q0Rhup_Vjlk",
      "https://www.youtube.com/watch?v=7QlvGBJ9Tng",
      "https://www.youtube.com/watch?v=cRiqZ0j1gEM",
      "https://www.youtube.com/watch?v=nKrQcXMBGRc"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Data Structures and Algo",
    videos: [
      "https://www.youtube.com/watch?v=2h433OItQiA",
      "https://www.youtube.com/watch?v=7P0qxxEy2-w",
      "https://www.youtube.com/watch?v=_71ENYohRiE",
      "https://www.youtube.com/watch?v=Dt6gzsNrghQ",
      "https://www.youtube.com/watch?v=QdMUBiTC2bM",
      "https://www.youtube.com/watch?v=TDjuWLwDPLQ",
      "https://www.youtube.com/watch?v=eeUUFDN0yyI",
      "https://www.youtube.com/watch?v=jxTyXvCNkL4",
      "https://www.youtube.com/watch?v=h30dpA8_rsQ",
      "https://www.youtube.com/watch?v=BLE6FwwmlUQ",
      "https://www.youtube.com/watch?v=NIqTEUeBXGE",
      "https://www.youtube.com/watch?v=_et0UKwhozU",
      "https://www.youtube.com/watch?v=GLTR39VIAdc",
      "https://www.youtube.com/watch?v=cGFPyhGzVY4",
      "https://www.youtube.com/watch?v=HBON-ooIygo",
      "https://www.youtube.com/watch?v=RxAPGNpb6cc",
      "https://www.youtube.com/watch?v=Gl9u9LRXpMY",
      "https://www.youtube.com/watch?v=HiT28-kHW3A",
      "https://www.youtube.com/watch?v=kZAdzQlkpk4",
    ]
  },
  {
    name: "System Design",
    videos: [
      "https://www.youtube.com/watch?v=43-X22tdxiI",
      "https://www.youtube.com/watch?v=z4AUhxIWKSM",
      "https://www.youtube.com/watch?v=MPxr1q8ORuA",
      "https://www.youtube.com/watch?v=cG3LMd2hIXY",
      "https://www.youtube.com/watch?v=IhemzDuCwgU",
      "https://www.youtube.com/watch?v=Cdh9qAwFNNk",
      "https://www.youtube.com/watch?v=2GKay0Mwk4U",
      "https://www.youtube.com/watch?v=rb2R5I9S5d8",
      "https://www.youtube.com/watch?v=27wYlcIYAO8",
      "https://www.youtube.com/watch?v=dHjHXis1r24",
      "https://www.youtube.com/watch?v=d9kA8CW8Cns",
      "https://www.youtube.com/watch?v=bIBC_RQtS2E",
      "https://www.youtube.com/watch?v=xBTGln828Ps",
      "https://www.youtube.com/watch?v=IaDU8_KjrpY",
      "https://www.youtube.com/watch?v=ZtpIzSZbuh0",
      "https://www.youtube.com/watch?v=VOrpRnE24KI",
      "https://www.youtube.com/watch?v=qxFj8X8n6CE",
      "https://www.youtube.com/watch?v=z7wB95TXB8M",
      "https://www.youtube.com/watch?v=o8HgXxqsYBc",
      "https://www.youtube.com/watch?v=xXtig5uLQS4",
      "https://www.youtube.com/watch?v=W7ppbYgrhwg",
      "https://www.youtube.com/watch?v=MyiLxH8St0U",
      "https://www.youtube.com/watch?v=6HKwwJOFHOY",
      "https://www.youtube.com/watch?v=1_8a8-__6ts",
      "https://www.youtube.com/watch?v=zaArcSrLPa8",
      "https://www.youtube.com/watch?v=SvBnrJKzH8k",
      "https://www.youtube.com/watch?v=B76BhEq1FN8",
      "https://www.youtube.com/watch?v=2x1L563nTlU",
      "https://www.youtube.com/watch?v=VPnYuwwg0rU",
      "https://www.youtube.com/watch?v=EYQijvnyYp0",
      "https://www.youtube.com/watch?v=dBtpV7aN_20",
      "https://www.youtube.com/watch?v=Q5jPD2ECEgM",
      "https://www.youtube.com/watch?v=9csfoQK2T8g",
      "https://www.youtube.com/watch?v=k8AObcX8azM"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "Kafka",
    videos: [
      "https://www.youtube.com/watch?v=DQFmUXSM-fA",
      "https://www.youtube.com/watch?v=lFox22RJE7s",
      "https://www.youtube.com/watch?v=bIaxc14te7U",
      "https://www.youtube.com/watch?v=cbAAMFjIaSw",
      "https://www.youtube.com/watch?v=xgIXpUCzScc",
      "https://www.youtube.com/watch?v=Ej0QC9GVziY",
      "https://www.youtube.com/watch?v=imVH0TXVkm8",
      "https://www.youtube.com/watch?v=m9AOYW2GF00",
      "https://www.youtube.com/watch?v=JWrVRILzoQs",
      "https://www.youtube.com/watch?v=vmuZaT6JpCM"
    ].map(v => ({ id: extractId(v), url: v }))
  },
  {
    name: "DevOps",
    videos: [
      "https://www.youtube.com/watch?v=ZbG0c87wcM8",
      "https://www.youtube.com/watch?v=apGV9Kg7ics",
      "https://www.youtube.com/watch?v=IPvYjXCsTg8",
      "https://www.youtube.com/watch?v=iwolPf6kN-k",
      "https://www.youtube.com/watch?v=IA90BTozdow",
      "https://www.youtube.com/watch?v=17Bl31rlnRM",
      "https://www.youtube.com/watch?v=KVBON1lA9N8",
      "https://www.youtube.com/watch?v=8YLsQIG2Svo",
      "https://www.youtube.com/watch?v=62N8UiWUdQo",
      "https://www.youtube.com/watch?v=QaPPSWHgd8c"
    ].map(v => ({ id: extractId(v), url: v }))
  }
];

module.exports = courses;